xdebug and app_dev

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,4 +1,4 @@
-FROM php:8.2-fpm
+FROM php:8.2-fpm as app
 
 # Install system dependencies
 RUN apt-get update && apt-get install -y \
@@ -10,6 +10,15 @@ RUN apt-get update && apt-get install -y \
 RUN pecl install redis \
     && docker-php-ext-enable redis \
     && docker-php-ext-install pdo pdo_mysql pcntl zip
+
+
+    # Useful PHP extension installer image, copy binary into your container
+#  COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
+
+# Install php extensions
+ # exit on errors, exit on unset variables, print every command as it is executed
+#  RUN set -eux; \
+#      install-php-extensions pdo pdo_mysql;
 
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
@@ -32,3 +41,10 @@ RUN composer install --prefer-dist --no-dev --no-scripts --no-progress --no-inte
 COPY ./app/ .
 
 RUN composer dump-autoload --optimize
+
+
+FROM app as app_dev
+# everything under app_dev will be used to build the app_dev image, as called in the docker-compose.dev.yaml file
+
+# RUN set -eux; \
+    # install-php-extensions xdebug;
